### ISSUE TITLE
Example provided with package fails with an error

### ISSUE THREAD

**Issue by gadgets-on-github** [valerycolong/vcard#5]
For me when I try to run the example given on the example page I end up with an error:

E/flutter (20581): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (20581): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (20581): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (20581): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:93:7)
E/flutter (20581): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:106:4)
E/flutter (20581): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:145:62)
E/flutter (20581): #3      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:151:35)
E/flutter (20581): #4      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (20581): #5      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (20581): #6      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
E/flutter (20581): #7      VCard.saveToFile (package:vcard/vcard.dart:141:29)
E/flutter (20581): #8      main (package:flutter_junk_vcard/main.dart:24:9)
E/flutter (20581): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (20581): #10     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (20581): #11     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (20581): #12     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (20581): #13     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (20581): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (20581): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (20581): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Here is the example code for reference:

import 'package:flutter/material.dart';
import 'package:vcard/vcard.dart';

void main() {

//  WidgetsFlutterBinding.ensureInitialized();

  ///Create a new vCard
  var vCard = VCard();

  ///Set properties
  vCard.firstName = 'FirstName';
  vCard.middleName = 'MiddleName';
  vCard.lastName = 'LastName';
  vCard.organization = 'ActivSpaces Labs';
  vCard.photo.attachFromUrl('https://www.activspaces.com/wp-content/uploads/2019/01/ActivSpaces-Logo_Dark.png', 'PNG');
  vCard.workPhone = 'Work Phone Number';
  vCard.birthday = DateTime.now();
  vCard.jobTitle = 'Software Developer';
  vCard.url = 'https://github.com/valerycolong';
  vCard.note = 'Notes on contact';

  /// Save to file
  vCard.saveToFile('./contact.vcf');

  /// Get as formatted string
  print(vCard.getFormattedString());

}

If I add the WidgetsFlutterBinding call and import package:flutter/meterial.dart (it's a requirement) then I get the following error instead:
E/flutter (21842): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot open file, path = '/data/user/0/com.example.rawl.flutter_junk_vcard/app_flutter/vCard/exports/./contact.vcf' (OS Error: No such file or directory, errno = 2)
E/flutter (21842): #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
E/flutter (21842): #1      _File.openSync (dart:io/file_impl.dart:479:5)
E/flutter (21842): #2      _File.writeAsBytesSync (dart:io/file_impl.dart:604:31)
E/flutter (21842): #3      _File.writeAsStringSync (dart:io/file_impl.dart:628:5)
E/flutter (21842): #4      VCard.saveToFile (package:vcard/vcard.dart:143:8)
E/flutter (21842): <asynchronous suspension>
E/flutter (21842): #5      main (package:flutter_junk_vcard/main.dart:24:9)
E/flutter (21842): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:233:25)
E/flutter (21842): #7      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (21842): #8      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (21842): #9      _runZoned (dart:async/zone.dart:1630:10)
E/flutter (21842): #10     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (21842): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:225:5)
E/flutter (21842): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (21842): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

So presumably I'm missing something, but I think I have followed the example closely, so ???

**Comment by gadgets-on-github** [comment]
FYI I am running Android Studio 4.0.1, Flutter 1.20.1-stable, and Dart 2.9.0.  VCard 0.1.1.  Would love to get this working.

**Comment by gadgets-on-github** [comment]
In the meantime I thought I'd upgrade everything.  I'm now running Android Studio 4.1, some updated plugins and other Studio related bits and piece, Flutter 1.20.1-stable, and Dart 2.9.0.  I'm still receiving the same error.
